# GitHub Action for generating a contribution graph with a snake eating your contributions
name: Generate Snake

# Controls when the action will run which runs every 6 hours
on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# this command allows to run the Action automatically from the Actions tab
  workflow_dispatch:

# the sequence of runs in this workflow is:
jobs:
  # this workflow's job
  build:
    # the runner needed by job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # checks repo under $GITHUB_WORKSHOP, so job can access it
      - uses: actions/checkout@v2

    # generates the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ gihub.repository_owner }}
          
          outputs: |
            dist/github-contribution-grid-snake.svg

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     # show the status of the build; makes it easier for debugging (if there's any issues)
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
